[package]
name = "client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy = {version="0.17", features = ["bevy_remote"]}
clap = { version = "4.5", features = ["derive"] }
base64 = "0.22"
image = "0.25"
crossbeam-channel.workspace = true
bridge = { path = "../bridge" }
tokio = { workspace = true }
